"""
Configuration for Topic Matcher project.
"""

from pathlib import Path

# Project paths
PROJECT_ROOT = Path(__file__).parent
DATA_DIR = PROJECT_ROOT / "data"
DATABASE_PATH = DATA_DIR / "database.db"

# Data sources configuration
SOURCES = {
    "arxiv": {
        "name": "arXiv",
        "type": "academic",
        "api_url": "http://export.arxiv.org/api/query",
        "categories": ["cs.AI", "cs.LG", "cs.CL", "stat.ML"],
        "max_results": 100,
    },
    "habr": {
        "name": "Habr",
        "type": "professional",
        "base_url": "https://habr.com",
        "feed_url": "https://habr.com/ru/rss/articles/",
    },
    "hackernews": {
        "name": "Hacker News",
        "type": "mass_media",
        "api_url": "https://hn.algolia.com/api/v1",
        "max_results": 50,
        "story_type": "top",  # top, best, new
    },
    "techcrunch": {
        "name": "TechCrunch",
        "type": "mass_media",
        "feed_url": "https://techcrunch.com/feed/",
        "max_results": 50,
    },
}

# Topic modeling parameters
TOPIC_MODEL = {
    "n_topics": 7,
    "min_document_frequency": 2,
    "max_document_frequency": 0.8,
    "n_top_words": 10,
}

# Keyword extraction parameters
KEYWORDS = {
    "n_keywords": 10,  # Number of keywords per article/topic
    "ngram_range": (1, 2),  # (1,1) = unigrams, (1,2) = bigrams, (1,3) = trigrams
    "min_df": 1,  # Minimum document frequency
}

# Preprocessing parameters
PREPROCESSING = {
    "min_word_length": 3,
    "max_word_length": 20,
    "russian_stopwords": [
        "и",
        "в",
        "во",
        "не",
        "что",
        "он",
        "на",
        "я",
        "с",
        "со",
        "как",
        "а",
        "то",
        "все",
        "она",
        "так",
        "его",
        "но",
        "да",
        "ты",
        "к",
        "у",
        "же",
        "вы",
        "за",
        "бы",
        "по",
        "только",
        "её",
        "мне",
        "было",
        "вот",
        "от",
        "меня",
        "ещё",
        "нет",
        "о",
        "из",
        "ему",
        "теперь",
        "когда",
        "уже",
        "вам",
        "ни",
        "быть",
        "был",
        "него",
        "до",
        "вас",
        "нибудь",
        "опять",
        "уж",
        "вам",
        "сказал",
        "ведь",
        "там",
        "потом",
        "себя",
        "ничего",
        "ей",
        "может",
        "они",
        "тут",
        "где",
        "есть",
        "надо",
        "ней",
        "для",
        "мы",
        "тебя",
        "их",
        "чем",
        "была",
        "сам",
        "чтоб",
        "без",
        "будто",
        "человек",
        "чего",
        "раз",
        "также",
        "себе",
        "под",
        "жизнь",
        "будет",
        "ж",
        "тогда",
        "кто",
        "этот",
        "говорил",
        "это",
    ],
    "english_stopwords": [
        "the",
        "a",
        "an",
        "and",
        "or",
        "but",
        "in",
        "on",
        "at",
        "to",
        "for",
        "of",
        "with",
        "by",
        "from",
        "as",
        "is",
        "was",
        "are",
        "were",
        "been",
        "be",
        "have",
        "has",
        "had",
        "do",
        "does",
        "did",
        "will",
        "would",
        "could",
        "should",
        "may",
        "might",
        "must",
        "shall",
        "can",
        "need",
        "dare",
        "ought",
        "used",
        "this",
        "that",
        "these",
        "those",
        "am",
        "its",
        "it",
        "i",
        "you",
        "he",
        "she",
        "we",
        "they",
        "what",
        "which",
        "who",
        "whom",
        "whose",
        "where",
        "when",
        "why",
        "how",
        "all",
        "each",
        "every",
        "both",
        "few",
        "more",
        "most",
        "other",
        "some",
        "such",
        "no",
        "nor",
        "not",
        "only",
        "own",
        "same",
        "so",
        "than",
        "too",
        "very",
        "just",
        "also",
    ],
}

# Comparison thresholds
COMPARISON = {
    "jaccard_threshold": 0.15,
    "cosine_threshold": 0.3,
}

# Deduplication thresholds
DEDUPLICATION = {
    "title_threshold": 0.7,
    "content_threshold": 0.85,
}
